<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import BaseButton from '@/components/BaseButton/index.vue'
import { workspaceApi } from '../api'
import type { Generation, Readiness, Workspace } from '../types'

const route=useRoute();const router=useRouter();const project=ref<Workspace|null>(null);const readiness=ref<Readiness|null>(null);const generations=ref<Generation[]>([]);const directoryName=ref('');const generating=ref(false);const error=ref('')
const id=computed(()=>String(route.params.id));const target=computed(()=>readiness.value?.targetPath.replace(/[^/]+$/,directoryName.value)||'')
async function load(){[project.value,readiness.value,generations.value]=await Promise.all([workspaceApi.getProject(id.value),workspaceApi.readiness(id.value),workspaceApi.generations(id.value)]);directoryName.value=readiness.value.suggestedDirectoryName}
async function generate(){generating.value=true;error.value='';try{const result=await workspaceApi.generate(id.value,directoryName.value);generations.value=[result,...generations.value];await load()}catch(e){error.value=(e as Error).message}finally{generating.value=false}}
onMounted(load)
</script>

  <template><section v-if="project&&readiness" class="generate"><header><button @click="router.push({name:'workspace-documents',params:{id,type:'prd'}})">← 返回文档</button><h1>生成模板仓库</h1><p>写入独立本机目录，并创建第一个 Git 存档点。</p></header><div class="generate__grid"><main><section><h2>生成检查</h2><dl><div><dt>项目类型</dt><dd>{{ project.presets.map(item => ({admin:'后台管理',website:'官网 / H5',tool:'业务工具'}[item])).join('、') }}</dd></div><div><dt>文档完整度</dt><dd>{{ readiness.completeness }}%</dd></div><div><dt>Git</dt><dd>自动初始化并提交</dd></div><div><dt>覆盖策略</dt><dd>禁止覆盖已有目录</dd></div></dl></section><section><h2>目标目录</h2><label>目录名<input v-model="directoryName" /></label><code>{{ target }}</code></section><section v-if="readiness.missing.length" class="missing"><h2>还需补充</h2><p v-for="item in readiness.missing" :key="`${item.documentType}-${item.fieldId}`">{{ item.documentType }} · {{ item.label }}</p></section><p v-if="error" class="error">{{ error }}</p><BaseButton :disabled="!readiness.ready||!directoryName" :loading="generating" @click="generate">生成到本机</BaseButton></main><aside><h2>生成记录</h2><p v-if="!generations.length">暂无记录</p><article v-for="item in generations" :key="item.id"><strong :class="item.status">{{ item.status==='success'?'成功':'失败' }}</strong><code>{{ item.targetPath }}</code><small>{{ new Date(item.createdAt).toLocaleString() }}</small></article></aside></div></section><div v-else class="loading">正在检查项目…</div></template>

<style scoped lang="less">.generate{max-width:1080px;margin:0 auto}.generate>header{margin-bottom:22px}.generate>header button{border:0;background:transparent;color:@color-text-secondary;padding:0;margin-bottom:12px;cursor:pointer}.generate h1{font-size:25px}.generate>header p{color:@color-text-secondary;margin-top:4px}.generate__grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px}.generate main,.generate aside{border:1px solid @color-border;border-radius:@radius-md;background:#fff;padding:22px}.generate main{display:flex;flex-direction:column;gap:24px}.generate h2{font-size:15px;margin-bottom:12px}dl>div{display:flex;justify-content:space-between;border-bottom:1px solid @color-border;padding:10px 0;font-size:13px}dt{color:@color-text-secondary}label{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:600}input{border:1px solid @color-border-strong;border-radius:@radius-sm;padding:10px}code{display:block;margin-top:9px;padding:9px;background:@color-bg-muted;border-radius:@radius-sm;color:#475569;font-size:12px;overflow-wrap:anywhere}.missing{border-left:3px solid @color-warning;padding-left:14px}.missing p{font-size:12px;color:@color-text-secondary;margin:5px 0}.error{color:@color-danger}.generate aside>p{font-size:13px;color:@color-text-secondary}.generate article{padding:12px 0;border-bottom:1px solid @color-border}.generate article strong{font-size:12px}.generate article strong.success{color:@color-success}.generate article strong.failed{color:@color-danger}.generate article small{display:block;margin-top:6px;color:@color-text-secondary}.loading{padding:80px;text-align:center;color:@color-text-secondary}@media(max-width:760px){.generate__grid{grid-template-columns:1fr}}
</style>
