<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import BaseButton from '@/components/BaseButton/index.vue'
import { useWorkspaceStore } from '../store'
import type { DeliveryTier, Preset, ProjectCreateInput } from '../types'

const store = useWorkspaceStore(); const router = useRouter(); const step = ref(1); const submitting = ref(false); const error = ref('')
const form = reactive({ name:'', slug:'', presets:['admin'] as Preset[], summary:'', deliveryTier:'business' as DeliveryTier, targetUsers:'', painPoints:'', successMetric:'', mustHave:'', excluded:'', roles:'项目负责人、普通用户', dataSensitivity:'normal' as ProjectCreateInput['dataSensitivity'], devices:['desktop'], expectedScale:'100 名以内用户，日常业务数据', integrations:'' })
onMounted(() => store.loadBootstrap())
function slugify() { if (!form.slug) form.slug = form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') }
const valid = computed(() => step.value === 1 ? form.name.length >= 2 && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug) && form.presets.length > 0 && form.summary.length >= 10 : step.value === 2 ? form.targetUsers.length >= 2 && form.painPoints.length >= 5 && form.successMetric.length >= 3 && form.mustHave.trim().length > 0 : form.roles.trim().length > 0 && form.expectedScale.trim().length > 0)
const split = (value:string) => value.split(/[\n,，]/).map(item=>item.trim()).filter(Boolean)
async function submit(){submitting.value=true;error.value='';try{const project=await store.createProject({...form,mustHave:split(form.mustHave),excluded:split(form.excluded),roles:split(form.roles),integrations:split(form.integrations)});await router.push({name:'workspace-documents',params:{id:project.id,type:'prd'}})}catch(e){error.value=(e as Error).message}finally{submitting.value=false}}
</script>

<template><section class="wizard"><header><button @click="router.back()">← 返回</button><div><span>步骤 {{ step }} / 3</span><h1>创建产研项目</h1></div></header><div class="steps"><b v-for="item in 3" :key="item" :class="{active:item<=step}"></b></div>
  <form @submit.prevent="step<3?step++:submit()"><div v-if="step===1" class="form-section"><h2>项目基础</h2><label>项目名称<input v-model="form.name" autofocus @blur="slugify" /></label><label>仓库目录名<input v-model="form.slug" placeholder="customer-insight" /><small>仅小写字母、数字和连字符</small></label><fieldset class="preset-options"><legend>项目类型 <small>可多选</small></legend><label v-for="preset in store.bootstrap?.presets" :key="preset.id"><input v-model="form.presets" type="checkbox" :value="preset.id" /><span><strong>{{ preset.name }}</strong><small>{{ preset.description }}</small></span></label></fieldset><label>项目摘要<textarea v-model="form.summary" rows="4" placeholder="用一句话说明为谁解决什么问题" /></label><label>交付档位<select v-model="form.deliveryTier"><option value="demo">演示版</option><option value="business">业务版</option><option value="commercial">商用版</option></select></label></div>
    <div v-else-if="step===2" class="form-section"><h2>需求目标</h2><label>目标用户<input v-model="form.targetUsers" /></label><label>当前痛点<textarea v-model="form.painPoints" rows="4" /></label><label>成功指标<input v-model="form.successMetric" placeholder="例如：处理时间从 4 小时降到 1 小时" /></label><label>首版必须有<textarea v-model="form.mustHave" rows="4" placeholder="每行一项" /></label><label>明确不做<textarea v-model="form.excluded" rows="3" placeholder="每行一项，可选" /></label></div>
    <div v-else class="form-section"><h2>使用与数据</h2><label>用户角色<textarea v-model="form.roles" rows="3" placeholder="每行一项" /></label><fieldset><legend>目标设备</legend><label><input v-model="form.devices" type="checkbox" value="desktop" /> 桌面端</label><label><input v-model="form.devices" type="checkbox" value="mobile" /> 手机端</label></fieldset><label>数据敏感性<select v-model="form.dataSensitivity"><option value="none">不保存业务数据</option><option value="normal">普通业务数据</option><option value="personal">个人信息</option><option value="sensitive">高敏感数据</option></select></label><label>预计规模<input v-model="form.expectedScale" /></label><label>第三方对接<textarea v-model="form.integrations" rows="3" placeholder="每行一项，没有可留空" /></label></div>
    <p v-if="error" class="error">{{ error }}</p><footer><BaseButton v-if="step>1" variant="ghost" type="button" @click="step--">上一步</BaseButton><BaseButton type="submit" :disabled="!valid" :loading="submitting">{{ step===3?'创建项目':'下一步' }}</BaseButton></footer></form></section></template>

<style scoped lang="less">.wizard{max-width:760px;margin:0 auto}.wizard>header{display:flex;gap:20px;align-items:flex-start;margin-bottom:16px}.wizard>header button{border:0;background:transparent;color:@color-text-secondary;cursor:pointer;padding:6px 0}.wizard>header span{font-size:12px;color:@color-primary}.wizard h1{font-size:25px}.steps{display:flex;gap:6px;margin-bottom:20px}.steps b{height:4px;flex:1;background:#e5e7eb;border-radius:2px}.steps b.active{background:@color-primary}form{border:1px solid @color-border;background:#fff;border-radius:@radius-md;padding:24px}.form-section{display:flex;flex-direction:column;gap:17px}.form-section h2{font-size:17px}.form-section>label{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:600}input,textarea,select{border:1px solid @color-border-strong;border-radius:@radius-sm;padding:10px;font:inherit;font-weight:400}small{font-weight:400;color:@color-text-secondary}fieldset{border:0;display:flex;gap:20px}legend{font-size:13px;font-weight:600;margin-bottom:8px}fieldset label{font-size:13px}.preset-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.preset-options legend{grid-column:1/-1}.preset-options>label{display:flex;gap:9px;align-items:flex-start;border:1px solid @color-border;border-radius:@radius-sm;padding:11px;cursor:pointer}.preset-options input{margin-top:2px;padding:0}.preset-options span{display:flex;flex-direction:column;gap:3px}.preset-options strong{font-size:13px}.error{color:@color-danger;margin-top:16px}footer{display:flex;justify-content:flex-end;gap:10px;margin-top:24px}@media(max-width:640px){form{padding:18px}.wizard>header{padding:0 4px}.preset-options{grid-template-columns:1fr}}
</style>
